### ISSUE TITLE
the default code can not run sucessfully

### ISSUE THREAD

**Issue by Whylickspittle** [SOTAMak1r/GVGEN#5]
root@C.13217217:/workspace/GVGEN$ python run_text.py --text_input "a green truck"
Namespace(recon_bg='white', dm_bg='white', save_ply=False, dm_ckpt_path='ckpts/text_dm.ckpt', recon_ckpt_path='ckpts/text_recon.ckpt', dm_cfg_path='configs/text_dm.json', recon_cfg_path='configs/text_recon.json', text_input='a green truck', seed=0)
/opt/conda/lib/python3.10/site-packages/pytorch_lightning/utilities/migration/utils.py:55: PossibleUserWarning: The loaded checkpoint was produced with Lightning v2.0.9.post0, which is newer than your current Lightning version: v2.0.9
  rank_zero_warn(
[INFO] condition model is ('clip', 'text')
/root/.cache/clip/ViT-L-14.pt
[INFO] Diffusion data type is gdf
[INFO] condition model is ('clip', 'text')
/root/.cache/clip/ViT-L-14.pt
[INFO] Diffusion data type is gs
[INFO] FINISH LOAD TWO MODEL !
[text input] a green truck
DDIM Sampler: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:13<00:00,  7.45it/s]

[INFO] time cost = 13.985810279846191 seconds
Traceback (most recent call last):
  File "/workspace/GVGEN/run_text.py", line 82, in <module>
    recover_x = recon_pipe.display(
  File "/workspace/GVGEN/models/igen.py", line 396, in display
    render_pkg = render(viewpoint_cam, self.process_test_x(x[-1]), background, mean_var=True)
  File "/workspace/GVGEN/gaussian_renderer/__init__.py", line 155, in render
    rendered_image, radii = rasterizer(
ValueError: too many values to unpack (expected 2)

我遇到了一些问题，首先这个requirements.txt文件应该是有问题的 pytorch后面跟个cuda11.8   （我将torch的三项给删了）
不能够正确的pip install -r requirements.txt
我不太确定我的 diff_gaussian_rasterization 是不是正确的安装
下面是我的指令  （cuda环境12.1）
mkdir -p ./extras/diff_gaussian_rasterization/third_party
git clone --branch 0.9.9.0 https://github.com/g-truc/glm.git ./extras/diff_gaussian_rasterization/third_party/glm
pip install ./extras/diff_gaussian_rasterization

然后我下载了这些ckpt权重,进行这个默认的测试
python run_text.py --text_input "a green truck"
出现了上述问题，你能帮我定位一下问题吗？  操作系统 ubuntu22.04 docker image:  pytorch/pytorch:2.2.0-cuda12.1-cudnn8-devel

**Comment by Whylickspittle** [comment]
需要对/workspace/GVGEN/gaussian_renderer/__init__.py 里的部分 进行修改，才能正常使用demo..
```
rasterizer_output = rasterizer(
            means3D=means3D,
            means2D=means2D,
            shs=shs,
            colors_precomp=colors_precomp,
            opacities=opacity,
            scales=scales,
            rotations=rotations,
            cov3D_precomp=cov3D_precomp
        )

        # 打印 rasterizer 的返回内容和数量
        print("Rasterizer output:", rasterizer_output)
        print("Number of returned values from rasterizer:", len(rasterizer_output))

        # 解包返回值，根据需要捕获多余值
        rendered_image = rasterizer_output[0]
        radii = rasterizer_output[1]
```
